### ISSUE TITLE
I always have an error AttributeError: 'cifar100' object has no attribute 'train_data'

### ISSUE THREAD

**Issue by Ilearning99** [ngailapdi/LWF#3]
AttributeError: 'cifar100' object has no attribute 'train_data'，how to solve it?

**Comment by lyj201002** [comment]
Use model.data instead

**Comment by lyj201002** [comment]
> AttributeError: 'cifar100' object has no attribute 'train_data'，how to solve it?
Use model.data instead

**Comment by ngailapdi** [comment]
Make sure you're using the correct PyTorch version. PyTorch version up to 1.0 should not encounter this issue. As far as I know PyTorch version 1.2 will have this issue
